### ISSUE TITLE
modifica metadato vocabolari controllati

### ISSUE THREAD

**Issue by RaffaAracri** [InailUfficio5/inail-ndc#2]
Rispetto ai file di vocabolari-controllati di seguito riportati:
settore_correlato_malattia,
decisione_istruttoria_esito_mortale,
grande_gruppo_tariffario,
definizione_amministrativa
è necessario riportare la proprietà  Dataset riferita non al vocabolario "dcat:Dataset" ma al "dcatapit:Dataset"

**Comment by bruno-marino** [comment]
Risolto nel commit [a67cdc8](https://github.com/InailUfficio5/inail-ndc/commit/a67cdc8535cc1a160abd621f50adf130cf0f5970)
