### ISSUE TITLE
modifica metadati Ontologie

### ISSUE THREAD

**Issue by RaffaAracri** [InailUfficio5/inail-ndc#3]
Rispetto ai file di ontologie di seguito riportati:
prestazioni_amministrative,
autoliquidazione,
core

è necessario riportare la proprietà  accessURL e downloadURL non come proprietà  di "dct" ma di "dcat"
al posto di "dct:accessURL" sostituire "dcat:accessURL" 
al posto di "dct:downloadURL" sostituire "dcat:downloadURL"

**Comment by bruno-marino** [comment]
Risolto nel commit [a67cdc8](https://github.com/InailUfficio5/inail-ndc/commit/a67cdc8535cc1a160abd621f50adf130cf0f5970)
