### ISSUE TITLE
Errore URI Ontologie e Vocabolari su schema.gov.it

### ISSUE THREAD

**Issue by Clou-dia** [InailUfficio5/inail-ndc#4]
**Comportamento attuale**

Per l'errore che si sta verificando sulle risorse semantiche (Ontologie e Vocabolari) su schema.gov.it
es. https://w3id.org/italia/work-accident/onto/core/ > risulta pagina di errore

**Modifiche suggerite**

- [ ] per il problema di errata configurazione dei puntamenti dei file di configurazione di accesso (.htaccess) > alleghiamo una nuova cartella workaccident che include i file .htaccess rivisti
[work-accident V2.zip](https://github.com/InailUfficio5/inail-ndc/files/13439866/work-accident.V2.zip)

- [ ] il nome della cartella deve essere uguale a quello del file (oltre che della risorsa referenziata) quindi
rinominare ciascuna cartella e nome dei relativi file (a meno di estensione) utilizzando il nome con il quale viene referenziata la risorsa (es. ontologia) nella sua URI
 
 a titolo di esempio   l’ontologia “adm_serv” corrisponde al nome file “prestazioni_amministrative.<estensione>” sotto la cartella “assets/ontologies/prestazioni” del git. In questo caso, l’htaccess gestisce la differenza tra nome cartella e file, ma non la differenza tra nome ontologia e nome file. Quindi è necessario rinominare la cartella git e relativi file in "adm_serv" a meno dell'estensione

@bruno-marino

**Comment by bruno-marino** [comment]
> * [ ]  per il problema di errata configurazione dei puntamenti dei file di configurazione di accesso (.htaccess) > alleghiamo una nuova cartella workaccident che include i file .htaccess rivisti
>   [work-accident V2.zip](https://github.com/InailUfficio5/inail-ndc/files/13439866/work-accident.V2.zip)

Abbiamo effettuato le stesse modifiche riportate nello zip e fatto una PR due giorni fa sul repo w3id; sono in attesa di approvazione.  https://github.com/perma-id/w3id.org/pull/3719

> * [ ]  il nome della cartella deve essere uguale a quello del file (oltre che della risorsa referenziata) quindi
>   rinominare ciascuna cartella e nome dei relativi file (a meno di estensione) utilizzando il nome con il quale viene referenziata la risorsa (es. ontologia) nella sua URI

Sistemato nei commit https://github.com/InailUfficio5/inail-ndc/commit/617fa7ecfb1f50053211413e68291bc6571f1040 e https://github.com/InailUfficio5/inail-ndc/commit/96025443700037ccca80b1cafa93ee716e3b9d33

> a titolo di esempio l’ontologia “adm_serv” corrisponde al nome file “prestazioni_amministrative.” sotto la cartella “assets/ontologies/prestazioni” del git. In questo caso, l’htaccess gestisce la differenza tra nome cartella e file, ma non la differenza tra nome ontologia e nome file. Quindi è necessario rinominare la cartella git e relativi file in "adm_serv" a meno dell'estensione

Ok, dovremo verificare che i file e le cartelle rinominati non necessitino di cambiamenti nelle regole .htaccess (es: riga 13 di .htaccess della cartella controlled-vocabulary => rewrite rule su icdx con percorso hard-coded). 
Possiamo intanto testare queste modifiche ed in caso aggiornare.

**Comment by bruno-marino** [comment]
Attività completate.
@Clou-dia se non ci sono problemi su schema.gov.it chiudo la issue.

**Comment by Clou-dia** [comment]
Certo, chiudo pure io. 
Grazie
