### ISSUE TITLE
ontologia adm_serv errore nella keyClass InfortunioSulLavoro

### ISSUE THREAD

**Issue by RRRoby** [InailUfficio5/inail-ndc#5]
Nell’ontologia adm_serv c’è un URI nella keyClass che non è giusto  https://urlsand.esvalabs.com/?u=https%3A%2F%2Fw3id.org%2Fitalia%2Fwork-accident%2Fonto%2Fadm_serv%2FnfortunioSulLavoro&e=2637b01d&h=5b1bba5d&f=y&p=y

Suggerimento: aggiungere le "I"
https://urlsand.esvalabs.com/?u=https%3A%2F%2Fw3id.org%2Fitalia%2Fwork-accident%2Fonto%2Fadm_serv%2FInfortunioSulLavoro&e=2637b01d&h=5b1bba5d&f=y&p=y

**Comment by bruno-marino** [comment]
Risolto in https://github.com/InailUfficio5/inail-ndc/commit/df03905e8bfd01b96664b25f38b4d89d79a49c2a
