### ISSUE TITLE
ontologia proc21 errore su adms:status

### ISSUE THREAD

**Issue by RRRoby** [InailUfficio5/inail-ndc#6]
Nell’ontologia proc21 il metadato adms:status non è ben valorizzato. Nel turtle sembra tutto catalogued e published. Nel .owl però c’è un evidente errore:<adms:status>draft</adms:catalogued>
<adms:status>draft</adms:published>
Qui è draft ma l'end-tag non è corretto. Questo errore dell’end-tag nel .owl fa sì che LODE sollevi un’eccezione
 https://urlsand.esvalabs.com/?u=https%3A%2F%2Fschema.gov.it%2Flode%2Fextract%3Furl%3Dhttps%3A%2F%2Fw3id.org%2Fitalia%2Fwork-accident%2Fonto%2Fproc21&e=2637b01d&h=82ead65c&f=y&p=y

**Comment by bruno-marino** [comment]
Risolto in https://github.com/InailUfficio5/inail-ndc/commit/df03905e8bfd01b96664b25f38b4d89d79a49c2a
