### ISSUE TITLE
nelle ontologie  "adm_serv", "core", "proc21" è errato downloadURL del distribution/ADM-SERV-RDF-XML

### ISSUE THREAD

**Issue by RRRoby** [InailUfficio5/inail-ndc#7]
downloadURL del distribution/ADM-SERV-RDF-XML è errato nel file "adm_serv", "core", "proc21"

suggerimento correggere con:
dcat:downloadURL <https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/ontologies/adm_serv/latest/adm_serv.owl>
dcat:downloadURL <https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/ontologies/core/latest/core.owl>
dcat:downloadURL <https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/main/assets/ontologies/proc21/latest/proc21.owl>

**Comment by bruno-marino** [comment]
Risolto in https://github.com/InailUfficio5/inail-ndc/commit/df03905e8bfd01b96664b25f38b4d89d79a49c2a
