### ISSUE TITLE
errore di visualizzazione di su Lodview di molti concetti delle ontologie core,  adm_serv , proc21

### ISSUE THREAD

**Issue by RRRoby** [InailUfficio5/inail-ndc#8]
La presenza nelle label dei concetti del carattere "\r" determina una incompleta visualizzazione si lodeview

Suggerimento rimuovere "\r" dalle label ma anche dai comment

**Comment by bruno-marino** [comment]
Risolto in https://github.com/InailUfficio5/inail-ndc/commit/df03905e8bfd01b96664b25f38b4d89d79a49c2a
